########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Description:
  This template creates an IAM role for configuring S3 srever access logs within each account - 's3_server_access_logs'
  solution in the repo, https://github.com/aws-samples/aws-security-reference-architecture-examples (sra-1u3sd7f8e)

Metadata:
  SRA:
    Version: 1.0
    Order: 2
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Properties
        Parameters:
          - pSRASolutionName
      - Label:
          default: Role Properties
        Parameters:
          - pAuditAccountId
          - pLogArchiveAccountId
          - pManagementAccountId
          - pS3ServerAccessLogsLambdaRoleName
          - pS3ServerAccessLogsRoleName
          - pEventBridgeRoleName

    ParameterLabels:
      pAuditAccountId:
        default: Audit Account ID
      pLogArchiveAccountId:
        default: Log Archive Account ID
      pManagementAccountId:
        default: Organization Management Account ID
      pS3ServerAccessLogsLambdaRoleName:
        default: S3 Server Access Logs Lambda Role Name
      pS3ServerAccessLogsRoleName:
        default: Se Server Access Logs Role
      pEventBridgeRoleName:
        default: Event Bridge Role Name

      pSRASolutionName:
        default: SRA Solution Name

Parameters:
  pAuditAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Audit account ID
    Type: String
  pLogArchiveAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Log Archive account ID
    Type: String
  pManagementAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Organization Management Account ID
    Type: String
  pS3ServerAccessLogsLambdaRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: sra-s3-server-access-logs-lambda
    Description: S3 Server Access Logs Lambda Role Name
    Type: String   
  pS3ServerAccessLogsRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: sra-s3-server-access-logs
    Description: S3 Server Access Logs Configuration IAM Role Name
    Type: String

  pEventBridgeRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: sra-eventbridge-configuration
    Description: S3 Server Access Logs IAM Role Name
    Type: String
  
  pSRASolutionName:
    AllowedValues: [sra-s3-server-access-logs]
    Default: sra-s3-server-access-logs
    Description: The SRA solution name. The default value is the folder name of the solution
    Type: String

Resources:
  rConfigurationRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Actions require * in resource
          - id: W28
            reason: Explicit name provided
    Properties:
      RoleName: !Ref pS3ServerAccessLogsRoleName
      Description: !Sub SRA role assumed by '${pS3ServerAccessLogsLambdaRoleName}' to enable the S3 server access logs
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:PrincipalArn:
                  - !Sub arn:${AWS::Partition}:iam::${pManagementAccountId}:role/${pS3ServerAccessLogsLambdaRoleName}
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${pManagementAccountId}:root
      Path: '/'      
      Policies:
        - PolicyName: sra-s3-server-access-logs-policy-organizations
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: OrganizationsListAccounts
                Effect: Allow
                Action: organizations:ListAccounts
                Resource: '*'

        - PolicyName: sra-s3-server-access-logs-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: S3ServerAccessLogs
                Effect: Allow
                Action:
                  - s3:GetBucketLogging
                  - s3:PutBucketLogging
                  - s3:GetBucketTagging
                  - s3:PutBucketTagging
                  - s3:GetBucketAcl
                  - s3:PutBucketAcl
                  - s3:GetAccountPublicAccessBlock
                Resource: '*'

        - PolicyName: sra-s3-server-access-logs-policy-iam
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowReadIamActions
                Effect: Allow
                Action: iam:GetRole
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*
      Tags:
        - Key: sra-solution
          Value: !Ref pSRASolutionName
