########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Description:
  This template creates an event rule to send S3 bucket update events in each member account to the home region of the management account. - 's3_server_access_logs' solution in the repo,
  https://github.com/aws-samples/aws-security-reference-architecture-examples 
Metadata:
  SRA:
    Version: 1.0
    Order: 4
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Properties
        Parameters:
          - pSRASolutionName
      - Label:
          default: Event Rule Properties
        Parameters:
          - pEventRuleRoleName
    ParameterLabels:
      pSRASolutionName:
        default: SRA Solution Name

Parameters:
  pEventRuleRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -].
    Default: sra-s3-server-access-logs-global-events
    Description: Event rule role name for putting events on the home region event bus
    Type: String
  pSRASolutionName:
    AllowedValues: [sra-s3-server-access-logs]
    Default: sra-s3-server-access-logs
    Description: The SRA solution name. The default value is the folder name of the solution.
    Type: String
  pManagementAccountId:
    Description: "Management Account Id"
    Type: String

Resources:
  rEventBridgeRuleRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Specific role name provided
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              Service:
                - events.amazonaws.com

       Policies:
        - PolicyName: sra-events
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: events:PutEvents
                Resource: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${pManagementAccountId}:event-bus/default
  
  rS3EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${pSRASolutionName}-forward-s3-events
      Description: SRA EventBridge forward S3 Server Access Logs events to home region in management account.
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - s3.amazonaws.com
          eventName:
            - PutBucketTagging
      State: ENABLED
      Targets:
        - Arn: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${pManagementAccountId}:event-bus/default
          Id: !Sub ${pSRASolutionName}-s3-events-to-home-region
          RoleArn: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${pEventRuleRoleName}
